repos:
-   repo: local
    hooks:
    -   id: doc-updater
        name: Update documentation with code changes
        entry: doc-updater
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies: ['openai>=1.0.0'] 